/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calso;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ClosetsTest {
    @Test void appHasAGreeting() {
        Closets classUnderTest = new Closets();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
